//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_with_Ajax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_students
    {
        public long id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public Nullable<long> dpt { get; set; }
    
        public virtual tbl_depart tbl_depart { get; set; }
    }
}
